spring:
  application:
    name: jocture-checker

  profiles:
    active : local

  datasource:
    list:
      - name: db-1
        url:  jdbc:h2:tcp://localhost/~/test
        username: sa
        password:
      - name: db-2
        url: jdbc:h2:tcp://localhost/~/testdsaasfsaf
        username: sal
        password:
      - name: db-3
        url: jdbc:h2:tcp://localhost/~/testdsaasfsaf
        username:
        password:
  #    - name: ${db3_name}
  #      url:  ${db3_url}
   #     username: ${db3_username}
   #     password:  ${db3_password}