spring:
  application:
    name: jocture-checker

  profiles:
    active: local

  datasource:
   # type: com.zaxxer.hikari.HikariDataSource  # FQCN(Fully Qualified Class Name)
  #  type: org.apache.commons.dbcp.BasicDataSource
    list:
      - name: db-1
        url:  jdbc:h2:tcp://localhost/~/test
        username: sa
        password:
      - name: db-2
        url: jdbc:h2:tcp://localhost/~/test
        username: sa
        password:

  #    - name: ${db3_name}
  #      url:  ${db3_url}
   #     username: ${db3_username}
   #     password:  ${db3_password}

logging:
  level:
    jocture.checker: DEBUG